[features]
seeds = false
skip-lint = false

[programs.localnet]
season_vault = "SeaSovAult111111111111111111111111111111111"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 15000

[test.validator]
url = "https://api.devnet.solana.com"

# NOTE:
# For devnet/mainnet stake-pool CPI, pass the correct stake-pool program id
# in initialize and do not use deprecated devnet program deployments.
